sudo: required
language: csharp
solution: src/RedisGeo.s1n
services:
  - docker
matrix:
  include:
    - os: linux
      dist: focal
      sudo: required
      dotnet: 8.0
      mono: none
      env: DOTNETCORE=8
script:
  - chmod +x ./deploy-envs.sh
  - chmod +x ./scripts/deploy.sh
  - cd scripts && chmod +x ./build.sh
  - chmod +x ./deploy.sh;