sudo: required
language: csharp
solution: src/RedisGeo.s1n
services:
  - docker
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      dotnet: 8.0.3
      mono: none
      env: DOTNETCORE=8
script:
  - chmod +x ./deploy-envs. sh
  - chmod Jscripts/build. sh
  - chmod +x . / scripts/deploy.sh
  - cd scripts && ./build.sh
  - if [ "STRAVIS_BRANCH" == "master" ]; then . /deploy.sh;